name: ci

on: 
  pull_request:

jobs:
  lint-bash-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint Bash scripts
        uses: docker://koalaman/shellcheck-alpine:v0.7.0
        with:
          args: .github/lint-scripts.sh

  ci:
    name: ci
    runs-on: ubuntu-latest
    needs: 
      - lint-bash-scripts
    env:
      HELM_VERSION: v3.2.4
    strategy:
      matrix:
        k8s-version:
         - v1.14.10
         - v1.15.12
         - v1.16.15
         - v1.17.11
         - v1.18.8
        keycloak-chart:
         # keycloak 11.0.2
         - 9.1.0
        keycloak-controller-chart:
         - 0.6.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: mvn build
        run: .github/mvn-build.sh
      - name: Create kind ${{ matrix.k8s-version }} cluster
        uses: helm/kind-action@master
        with:
          config: .github/kind-config.yaml
          node_image: kindest/node:${{ matrix.k8s-version }}
      - name: build docker image & push to kind nodes
        run: .github/docker-build.sh
      - name: test keycloak-controller
        run: .github/k8s-install.sh ${{ matrix.keycloak-chart }} ${{ matrix.keycloak-controller-chart }} ${{ matrix.k8s-version }}
